namespace EVarlik.Common.Enum
{
    public enum ResultStatus
    {
        UnknownError = -1,
        Success = 0,
        ForeignKeyConstraint = 1,
        MissingRequiredParamater = 2,
        InValidParamater = 3,
        Unauthorized = 4,
        NoSuchObject = 5,
        AlreadyAdded = 6,
        IndexOutOfBound = 7,
        NoPrimaryKey = 8,
        UnsupportedOperation = 9,
        LoginFailed = 10,
        SessionNotValid = 11,
        PropertyNotFound = 12,
        UnQualifiedPrivilege = 13,
        SessionTimeout = 14,
        InMemoryDatabaseError = 15,
        SerializationError = 16,
        NoLicence = 17,
        AlreadyDeleted = 18,
        DeleteControlError = 19,
        HasMessage = 20,
        BadData = 21,
        AllOfDataNotCommitted = 22,
        TransactionRollback = 23,
        RedisStoreError = 24,
        RedisError = 25,
        RootMailNotVerified = 26,
        MailNotVerified = 27,
        PassiveUser = 28,
        MailAlreadyVerified = 29,
        TenantNotFound = 30,
        LicenceNotFound = 31,
        LicenceCreditHasNoBalance = 32,
        AccountLocked = 33,
        DataModified = 34,
        TenantDoesNotHaveThisObject = 35,
        TokenGenerationError = 36,
        TokenTimedOut = 37,
        ThisIsYourCompany = 38,
        MoreThanOneUserGroup = 39,
        MaxCountReached = 40,
        MimeTypeNotAllowed = 41,
        MoreThanMaxSize = 42,
        DifferentTenant = 43,
        NotSufficentBalance = 44,
        AlreadyHaveAnAddress = 45,
        UserDoesNotHaveThisAddress = 46,
        AboveTheLimit = 47,
        CannotBeCancelled = 48
    }
}